### ISSUE TITLE
Strange indents

### ISSUE THREAD

**Issue by bullbesh** [SeanJxie/PyWirelessTransfer#1]
Can you explain, for what these two indents here?

![Screenshot_20210815-081254_GitHub.jpg](https://user-images.githubusercontent.com/69913622/129467886-9706c4d1-ba4d-4d0e-870b-928204dc514c.jpg)

**Comment by bullbesh** [comment]
I mean 72 and 73 strokes

**Comment by SeanJxie** [comment]
Just for visual formatting.
